
redis:
  host: localhost
  port: 7809

jwt:
  access-token:
    secret-key: ${JWT_ACCESS_TOKEN_SECRET_KEY:jwt-access-token-secret-key}
    valid-seconds: 300
  refresh-token:
    secret-key: ${JWT_REFRESH_TOKEN_SECRET_KEY:jwt-refresh-token-secret-key}
    valid-seconds: 604800

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 823010453529-vtpf78akl4dc0rn8s9uq649v1crtpn0t.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
          naver:
            client-id: PyqTi2mMDkpj2i9Y22z4
            client-secret: kSKrKX7XYO
            authorization-grant-type: authorization_code
            client-name: re100Naver
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope: profile,email
          kakao:
            client-id: f85b2099323eb29df38f7a0148c219b0
            client-secret: TOHAzPPhCT6xaSBWOrsjocp4IdVHGJ7w
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: re100Kakao
            redirect-uri: http://localhost:8081/login/oauth2/code/kakao
            #                        scope: openid,profile_nickname,profile_image,account_email
            scope: profile_nickname,profile_image,account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            # OpenID Connect 일 경우 jwkSet URI 를 가져와야 하기 때문에 필수항목
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # OpenID Connect 로 인가서버와 통신하지 않을 경우

            # OpenID Connect 일 경우 nameAttributeKey 가 sub 이기 때문에 별도의 커스트 마이징이 필요
            # CustomOidcUserService 참조
            # user-name-attribute: sub
  mvc:
    static-path-pattern: /static/**