spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET:apps.googleusercontent.com}
            scope: profile, email
          naver:
            client-id: PyqTi2mMDkpj2i9Y22z4
            client-secret: kSKrKX7XYO
            authorization-grant-type: authorization_code
            client-name: springsecurity
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: profile, email
          kakao:
            client-id: ${KAKAO_CLIENT_ID:apps.kakaousercontent.com}
            client-secret: ${KAKAO_CLIENT_SECRET:apps.kakaousercontent.com}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: springsecurity
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, profile_image, account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id