spring:
  config:
    import:
      - classpath:properties/cors.yml
      - classpath:properties/jwt.yml
      - classpath:properties/redis.yml
      - classpath:properties/oauth.yml

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:boot2;MODE=MYSQL
    username: sa

  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true