spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 719209830145-mi8pdn51ivofbkvt1oim8r2a3r07bc4l.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: PyqTi2mMDkpj2i9Y22z4
            client-secret: kSKrKX7XYO
            authorization-grant-type: authorization_code
            client-name: lingotown
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: profile, email
          kakao:
            client-id: ff9a59afd70763b90afba45d45849afb
            client-secret: RKc7lhavKEBos5tePIAjZJ4D5kKKxc6g
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: lingotown
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, profile_image, account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            issuer-uri: https://kauth.kakao.com
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id